# fly.toml app configuration file generated for gotwhat on 2023-08-03T02:24:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gotwhat"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
